FROM buildnode

RUN git clone -o gh --depth=1 https://github.com/opencog/cogutils.git
RUN git clone -o gh --depth=1 https://github.com/opencog/atomspace.git
RUN git clone -o gh --depth=1 https://github.com/opencog/opencog.git
