FROM buildnode

MAINTAINER Dmitry Ponyatov "dponyatov@gmail.com"

#RUN git clone -o gh --depth=1 https://github.com/opencog/cogutils.git
#RUN git clone -o gh --depth=1 https://github.com/opencog/atomspace.git
#RUN git clone -o gh --depth=1 https://github.com/opencog/opencog.git
ADD cogutils /cogutils
ADD atomspace /atomspace
ADD opencog /opencog
