FROM gitclone
#FROM alpine
#FROM scratch
#FROM busybox
#FROM ubuntu:14.04

MAINTAINER Dmitry Ponyatov "dponyatov@gmail.com"

# RUN apk add --no-cache bash sudo
# RUN apk add --no-cache binutils llvm4

#ADD https://github.com/opencog/ocpkg/raw/master/ocpkg /tmp/ocpkg
#RUN chmod +x /tmp/ocpkg
#RUN /tmp/ocpkg -rdpvl
